FROM node:20

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install -g serve
RUN npm install axios
RUN npm install

COPY frontend ./

RUN npm run build

EXPOSE 3000

CMD ["serve", "-s", "build"]